"""Add host_port to deployment_containers

Revision ID: 684f267b0e8b
Revises: 2e17cdd8f496
Create Date: 2026-03-27 17:43:09.932937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '684f267b0e8b'
down_revision: Union[str, Sequence[str], None] = '2e17cdd8f496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployment_containers', sa.Column('host_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployment_containers', 'host_port')
    # ### end Alembic commands ###
