"""actually_add_logging_fields

Revision ID: 777cc02a2dbe
Revises: edf9b8165966
Create Date: 2026-04-10 08:48:33.971112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '777cc02a2dbe'
down_revision: Union[str, Sequence[str], None] = 'edf9b8165966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployment_containers', sa.Column('lifecycle_phase', sa.String(length=50), nullable=True))
    op.add_column('deployment_containers', sa.Column('last_error', sa.String(), nullable=True))
    op.add_column('deployment_containers', sa.Column('build_logs', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployment_containers', 'build_logs')
    op.drop_column('deployment_containers', 'last_error')
    op.drop_column('deployment_containers', 'lifecycle_phase')
    # ### end Alembic commands ###
